import time

print("My name is Doctor Strange. What is your name?")
name = input()
print(f"Welcome {name}, I am going to perform a mind trick on you.")
time.sleep(3)
print("Pick a number between 1 and 10")
time.sleep(2)
number = input()
print("Multiply the number by 2")
time.sleep(4)
print("Multiply the new number by 5")
time.sleep(4)
print("Divide the current number by the original number")
time.sleep(4)
print("Subtract 7 from the current number")
time.sleep(4)
print("Wait! The wizard is reading your mind.")
time.sleep(2)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)
guess = int(int(number) * 2 * 5 / int(number) - 7)
print(f"The number that you are thinking now is {guess}")


